root: true
env:
  es2022: true
  node: true
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2022
  sourceType: module
plugins:
  - '@typescript-eslint'
extends:
  - 'plugin:@typescript-eslint/recommended'
rules:
  quotes:
    - error
    - single
  semi:
    - error
    - always
  max-len:
    - error
    - 80
  no-unused-vars:
    - error
ignorePatterns:
  - node_modules/
  - dist/
  - coverage/
  - .eslintrc.yml
